import json
import os
import re
from pathlib import Path
from typing import Dict, Any, List, Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# ==========================================
# 1. GLOBAL CONFIGURATION & STYLING
# ==========================================

BASE_RESULTS_DIR = "./results"
FIGURE_OUTPUT_DIR = "./figures/step14_martfl_collusion"

# --- Naming Standards ---
PRETTY_NAMES = {
    # Datasets
    "cifar10": "CIFAR-10",
    "cifar100": "CIFAR-100",
    "fashion_mnist": "Fashion-MNIST",
    "trec": "TREC (Text)",
    "texas100": "Texas100 (Tabular)",
    "purchase100": "Purchase100 (Tabular)",

    # Attack Modes
    "random": "Random Noise",
    "inverse": "Inverse Gradient",
}

def format_label(label: str) -> str:
    if not isinstance(label, str): return str(label)
    return PRETTY_NAMES.get(label.lower(), label.replace("_", " ").title())

def set_publication_style():
    """Sets the 'Big & Bold' professional style."""
    sns.set_theme(style="whitegrid")
    sns.set_context("paper", font_scale=1.8)
    plt.rcParams.update({
        'font.family': 'sans-serif',
        'font.weight': 'bold',
        'axes.labelweight': 'bold',
        'axes.titleweight': 'bold',
        'axes.titlesize': 24,
        'axes.labelsize': 22,
        'xtick.labelsize': 16, # Slightly smaller for long dataset names
        'ytick.labelsize': 18,
        'axes.linewidth': 2.5,
        'axes.edgecolor': '#333333',
        'lines.linewidth': 3.0,
        'figure.figsize': (14, 8),
    })

# ==========================================
# 2. DATA LOADING & PARSING
# ==========================================

def parse_scenario_name(scenario_name: str) -> Dict[str, str]:
    """
    Parses folder names generated by your Step 13/14 script.
    Format: step14_collusion_{MODE}_martfl_{DATASET}
    """
    try:
        # Regex captures Mode and Dataset. Defense is fixed to 'martfl'.
        pattern = r'step14_collusion_(random|inverse)_martfl_(.*)'
        match = re.search(pattern, scenario_name)
        if match:
            return {
                "attack_mode": match.group(1),
                "defense": "martfl",
                "dataset": match.group(2)
            }
    except Exception:
        pass
    return {"defense": "unknown"}

def load_run_data(metrics_file: Path) -> Dict[str, Any]:
    try:
        with open(metrics_file, 'r') as f:
            metrics = json.load(f)

        # We need the selection rate from the report
        report_file = metrics_file.parent / "marketplace_report.json"
        adv_selection_rate = 0.0

        if report_file.exists():
            with open(report_file, 'r') as f:
                report = json.load(f)
            sellers = report.get('seller_summaries', {}).values()
            adv = [s for s in sellers if s.get('type') == 'adversary']
            if adv:
                adv_selection_rate = np.mean([s['selection_rate'] for s in adv])

        # High Adv Selection = Successful Baseline Hijack
        return {
            "hijack_rate": adv_selection_rate * 100,
            "acc": metrics.get('acc', 0) * 100 if metrics.get('acc', 0) <= 1.0 else metrics.get('acc', 0)
        }
    except:
        return {}

def collect_martfl_data(base_dir: str) -> pd.DataFrame:
    all_runs = []
    base_path = Path(base_dir)
    print(f"Searching for MartFL Collusion results in {base_path}...")

    # Filter for step14 folders containing 'martfl'
    folders = [f for f in base_path.glob("step14_collusion_*") if "martfl" in f.name]

    for folder in folders:
        run_scenario = parse_scenario_name(folder.name)
        if run_scenario.get("defense") != "martfl": continue

        for metrics_file in folder.rglob("final_metrics.json"):
            run_metrics = load_run_data(metrics_file)
            if run_metrics:
                all_runs.append({**run_scenario, **run_metrics})

    df = pd.DataFrame(all_runs)
    if not df.empty:
        df['dataset'] = df['dataset'].apply(format_label)
        df['attack_mode'] = df['attack_mode'].apply(format_label)
    return df

# ==========================================
# 3. PLOTTING FUNCTION
# ==========================================

def plot_martfl_comprehensive_hijack(df: pd.DataFrame, output_dir: Path):
    print("\n--- Plotting MartFL Comprehensive Hijack Analysis ---")

    # Focus on the standard "Random Noise" Oracle attack
    mode = "Random Noise"
    subset = df[df['attack_mode'] == mode].copy()

    if subset.empty:
        print(f"No data for mode '{mode}'. Using all available data.")
        subset = df.copy()

    # Logical ordering of datasets (Simpler -> Complex)
    desired_order = [
        "Texas100 (Tabular)", "Purchase100 (Tabular)",
        "TREC (Text)",
        "CIFAR-10", "CIFAR-100"
    ]
    # Filter order to include only what exists in the data
    dataset_order = [d for d in desired_order if d in subset['dataset'].unique()]

    # If we have datasets not in the list, append them at the end
    remaining = [d for d in subset['dataset'].unique() if d not in dataset_order]
    dataset_order.extend(remaining)

    # Setup Figure
    plt.figure(figsize=(14, 8))

    # Create Bar Plot
    ax = sns.barplot(
        data=subset,
        x='dataset',
        y='hijack_rate',
        order=dataset_order,
        color="#e74c3c", # Red indicates Danger/Vulnerability
        edgecolor='black',
        linewidth=2.5,
        errorbar='sd',
        capsize=0.1
    )

    # --- Styling ---
    ax.set_title("MartFL Vulnerability: Baseline Hijack Rate", pad=20)
    ax.set_ylabel("Hijack Success Rate (%)", labelpad=15)
    ax.set_xlabel("", labelpad=15) # Dataset names are self-explanatory
    ax.set_ylim(0, 105)

    # Rotate x-labels if they are long (like the tabular ones)
    plt.xticks(rotation=15, ha='right')

    # Add "Compromised" Threshold Line
    ax.axhline(y=50, color='#333333', linestyle='--', linewidth=2, alpha=0.8)
    ax.text(len(dataset_order)-1, 52, "System Compromised (>50%)",
            fontsize=14, fontweight='bold', color='#333333', ha='right')

    # Annotate Bars
    for p in ax.patches:
        height = p.get_height()
        if height > 0:
            ax.annotate(f'{height:.0f}%',
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        xytext=(0, 8), textcoords='offset points',
                        fontsize=16, fontweight='bold')

    # Save
    fname = output_dir / "Step14_MartFL_Hijack_Comprehensive.pdf"
    plt.savefig(fname, bbox_inches='tight', dpi=300)
    print(f"  Saved: {fname}")
    plt.close()

def main():
    # 1. Apply Style
    set_publication_style()

    output_dir = Path(FIGURE_OUTPUT_DIR)
    os.makedirs(output_dir, exist_ok=True)
    print(f"Output Directory: {output_dir.resolve()}")

    # 2. Load Data
    df = collect_martfl_data(BASE_RESULTS_DIR)

    if df.empty:
        print("No MartFL collusion data found.")
        return

    # 3. Generate Plot
    plot_martfl_comprehensive_hijack(df, output_dir)

    print("\nAnalysis complete.")

if __name__ == "__main__":
    main()